Reorganize source and package directory structure

diff --git a/wrender b/wrender
--- a/wrender
+++ b/wrender
@@ -343,9 +343,6 @@ STEP DESCRIPTIONS (IN ORDER OF BUILD STEPS)
         * Iterate through the setlist (SETLIST_SYMLINK), creating the requested
           symbolic links in the chroot (union mounted) file system.
 
-        * Add the new platform environment's name to the chroot (union mounted)
-          system's environment variables.
-
         * Add the new platform environment's install path to the chroot (union
           mounted) system's environment variables.
 
@@ -836,14 +833,19 @@ echo 'CHECKING SOURCE'
 echo '---------------'
 echo
 
+# platform source file paths
+path_platform_env=$path_dir_source/copy/lib/platform-env
+path_platform_conf=$path_dir_source/copy/etc/platform.conf
+path_setlist=$path_dir_source/setlist
+
 # platform-env
 RUN_ENV_PLATFORM_PATH=""
 RUN_ENV_PLATFORM_NAME=""
-test -f "$path_dir_source/platform-env" \
-    && . "$path_dir_source/platform-env" \
+test -f "$path_platform_env" \
+    && . "$path_platform_env" \
     || fail "Unable to load required source file: \"platform-env\""
-test -f "$path_dir_source/conf/platform.conf" \
-    && . "$path_dir_source/conf/platform.conf" \
+test -f "$path_platform_conf" \
+    && . "$path_platform_conf" \
     || fail "Unable to load required source file: \"conf/platform.conf\""
 for i in \
     RUN_ENV_PLATFORM_NAME \
@@ -865,8 +867,8 @@ SETLIST_COPY=""
 SETLIST_SYMLINK=""
 SETLIST_UNINSTALL=""
 SETLIST_INSTALL=""
-test -f "$path_dir_source/setlist" \
-    && . "$path_dir_source/setlist" \
+test -f "$path_setlist" \
+    && . "$path_setlist" \
     || fail "Unable to load required source file: \"setlist\""
 test x"$SETLIST_COPY" = x \
     && fail "Required variable not defined by source files: SETLIST_COPY"
@@ -1165,17 +1167,17 @@ if test x"$should_install" = x1; then
         mount --bind "$path_dir_source/install" "$path_dir_tmp/$name_dir_union/mnt" \
             || fail "Unable to bind package install directory to chroot environment"
         for i in $SETLIST_INSTALL; do
-            package=`echo "$path_dir_source/install/${i}_"*.deb | sort --version-sort --reverse | head -n1`
-            test x"$package" != "$path_dir_source/install/${i}_*.deb" -a -f "$package" \
+            package_path=`echo "$path_dir_source/install/${i}_"*.deb | sort --version-sort --reverse | head -n1`
+            test x"$package_path" != "$path_dir_source/install/${i}_*.deb" -a -f "$package_path" \
                 || fail "Unable to find package: \"$i\""
-            package=`basename "$package"`
+            package_name=`basename "$package_path"`
 
             echo
-            echo "Installing Package: $i ($package)"
+            echo "Installing Package: $i ($package_name)"
             echo
 
-            chroot "$path_dir_tmp/$name_dir_union" dpkg -i "/mnt/$package" \
-                || fail "Unable to install package: \"$package\""
+            chroot "$path_dir_tmp/$name_dir_union" dpkg -i "/mnt/$package_name" \
+                || fail "Unable to install package: \"$package_name\""
         done
 
         # unmount bound chroot install directory
